name: iasi
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - numpy=1.16.1
  - pandas=0.24.1
  - matplotlib=3.0.2
  - jupyter=1.0.0
  - scipy=1.2.1
  - luigi=2.8.3
  - scikit-learn=0.21.2
  - netcdf4=1.4.2
  - luigi=2.8.3
  - python-dateutil=2.7.5
  - cartopy=0.17
  - seaborn=0.9.0
  - hdbscan=0.8.22
